# Generated by Django 5.2.4 on 2025-07-11 09:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentapplication',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RemoveField(
            model_name='agentapplication',
            name='approved',
        ),
        migrations.AddField(
            model_name='agentapplication',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentapplication',
            name='business_license',
            field=models.FileField(blank=True, help_text='Business license or registration (PDF, JPG, JPEG, PNG)', null=True, upload_to='agent_documents/license/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='agentapplication',
            name='id_document',
            field=models.FileField(blank=True, help_text='Valid ID document (PDF, JPG, JPEG, PNG)', null=True, upload_to='agent_documents/id/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='agentapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Resume or CV (PDF, DOC, DOCX)', null=True, upload_to='agent_documents/resume/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='agentapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
