version: '3.8'

services:
  web:
    build: .
    command: gunicorn cargo_ghana_engine.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - RUN_COLLECTSTATIC=true
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  celery:
    build: .
    command: celery -A cargo_ghana_engine worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - RUN_COLLECTSTATIC=false
    depends_on:
      - redis
      - web

  celery-beat:
      build: .
      command: [
        "celery", "-A", "cargo_ghana_engine", "beat",
        "--loglevel=info",
        "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"
      ]
      volumes:
        - .:/app
      env_file:
        - .env
      environment:
        - RUN_COLLECTSTATIC=false
      depends_on:
        - redis
        - web





# version: '3.8'

# services:
#   web:
#     build: .
#     command: gunicorn cargo_ghana_engine.wsgi:application --bind 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - '8000:8000'
#     env_file:
#       - .env
#     depends_on:
#       - redis

#   redis:
#     image: redis:7-alpine
#     ports:
#       - '6379:6379'

#   celery:
#     build: .
#     command: celery -A cargo_ghana_engine worker --loglevel=info
#     volumes:
#       - .:/app
#     env_file:
#       - .env
#     depends_on:
#       - redis
#       - web

#   celery-beat:
#     build: .
#     command: celery -A cargo_ghana_engine beat --loglevel=info \
#              --scheduler django_celery_beat.schedulers:DatabaseScheduler
#     volumes:
#       - .:/app
#     env_file:
#       - .env
#     depends_on:
#       - redis
#       - web
