# Generated by Django 5.2.4 on 2025-07-11 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='referral',
            name='last_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='link_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='reward_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='reward_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='successful_referrals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referral',
            name='total_referrals',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referral',
            name='total_reward_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['code'], name='referrals_r_code_559b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['email'], name='referrals_r_email_158686_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['reward_status'], name='referrals_r_reward__02730e_idx'),
        ),
    ]
