# Generated by Django 5.2.4 on 2025-07-11 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', 'add_predefined_boxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_count', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_logs', to='bookings.containerbatch')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
