# Generated by Django 5.2.4 on 2025-07-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_containercapacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerbatch',
            name='volume_history',
            field=models.JSONField(default=list, help_text='Historical volume data'),
        ),
    ]
