# Generated by Django 5.2.4 on 2025-07-07 16:26

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference_code',
            field=models.CharField(blank=True, default=bookings.models.generate_reference_code, editable=False, help_text='Short code for customer reference', max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Automatically computed', max_digits=10),
        ),
    ]
