# Generated by Django 5.2.4 on 2025-07-07 16:34

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_populate_reference_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference_code',
            field=models.CharField(default=bookings.models.generate_reference_code, editable=False, help_text='Short code for customer reference', max_length=12, unique=True),
        ),
    ]
