# Generated by Django 5.2.4 on 2025-07-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_reference_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_volume', models.DecimalField(decimal_places=2, help_text='Target volume (m³) for this container batch', max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ready', 'Ready to Ship'), ('dispatched', 'Dispatched')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
