# Generated by Django 5.2.4 on 2025-07-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_notificationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of boxes of this type'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Automatically computed as volume (m³) × £453.66', max_digits=10),
        ),
    ]
