# Generated by Django 5.2.4 on 2025-07-09 11:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_booking_weight_kg_booking_quantity_and_more'),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referrals.referral'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Computed as volume (m³) × £453.66', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='containerbatch',
            name='target_volume',
            field=models.DecimalField(decimal_places=2, default=Decimal('66.16'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='payload',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
